name: message_handler
description: This package aims to facilitate the use of alert messages for customers, as well as the execution of middlewares if necessary.
version: 1.0.1
repository: https://github.com/netogdn999/message_handler

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
